[2024-02-26T08:39:41.741+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yearly.Get_stockinfo_quarter manual__2024-02-26T08:19:15.571011+00:00 [queued]>
[2024-02-26T08:39:41.746+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yearly.Get_stockinfo_quarter manual__2024-02-26T08:19:15.571011+00:00 [queued]>
[2024-02-26T08:39:41.747+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2024-02-26T08:39:41.753+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Get_stockinfo_quarter> on 2024-02-26 08:19:15.571011+00:00
[2024-02-26T08:39:41.759+0000] {standard_task_runner.py:60} INFO - Started process 194 to run task
[2024-02-26T08:39:41.762+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'yearly', 'Get_stockinfo_quarter', 'manual__2024-02-26T08:19:15.571011+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpa9fqo1iy']
[2024-02-26T08:39:41.763+0000] {standard_task_runner.py:88} INFO - Job 122: Subtask Get_stockinfo_quarter
[2024-02-26T08:39:41.803+0000] {task_command.py:423} INFO - Running <TaskInstance: yearly.Get_stockinfo_quarter manual__2024-02-26T08:19:15.571011+00:00 [running]> on host 54ddb3ab1064
[2024-02-26T08:39:41.854+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nguyentuanduong555@gmail.com' AIRFLOW_CTX_DAG_OWNER='Duong_' AIRFLOW_CTX_DAG_ID='yearly' AIRFLOW_CTX_TASK_ID='Get_stockinfo_quarter' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T08:19:15.571011+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T08:19:15.571011+00:00'
[2024-02-26T08:39:41.979+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/plugin/pyspark_gcs_bq.py", line 9, in get_file_gcs_bq
    SparkSession
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-02-26T08:39:41.990+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=yearly, task_id=Get_stockinfo_quarter, execution_date=20240226T081915, start_date=20240226T083941, end_date=20240226T083941
[2024-02-26T08:39:41.999+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 122 for task Get_stockinfo_quarter ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 194)
[2024-02-26T08:39:42.018+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T08:39:42.033+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
