[2024-02-26T16:02:34.499+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yearly.Send_to_bq manual__2024-02-26T15:57:23.651069+00:00 [queued]>
[2024-02-26T16:02:34.504+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yearly.Send_to_bq manual__2024-02-26T15:57:23.651069+00:00 [queued]>
[2024-02-26T16:02:34.504+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 4
[2024-02-26T16:02:34.510+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): Send_to_bq> on 2024-02-26 15:57:23.651069+00:00
[2024-02-26T16:02:34.515+0000] {standard_task_runner.py:60} INFO - Started process 9515 to run task
[2024-02-26T16:02:34.518+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'yearly', 'Send_to_bq', 'manual__2024-02-26T15:57:23.651069+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpw_a9vldb']
[2024-02-26T16:02:34.519+0000] {standard_task_runner.py:88} INFO - Job 209: Subtask Send_to_bq
[2024-02-26T16:02:34.553+0000] {task_command.py:423} INFO - Running <TaskInstance: yearly.Send_to_bq manual__2024-02-26T15:57:23.651069+00:00 [running]> on host 756a22f68d7e
[2024-02-26T16:02:34.607+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nguyentuanduong555@gmail.com' AIRFLOW_CTX_DAG_OWNER='Duong_' AIRFLOW_CTX_DAG_ID='yearly' AIRFLOW_CTX_TASK_ID='Send_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T15:57:23.651069+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T15:57:23.651069+00:00'
[2024-02-26T16:02:34.608+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-26T16:02:34.608+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'gcloud dataproc jobs submit pyspark gs://datastocks123/pyspark_gcs_bq.py --cluster=dataproc --region=us-central1 --project=just-shell-415015']
[2024-02-26T16:02:34.621+0000] {subprocess.py:86} INFO - Output:
[2024-02-26T16:02:35.688+0000] {subprocess.py:93} INFO - ERROR: (gcloud.dataproc.jobs.submit.pyspark) You do not currently have an active account selected.
[2024-02-26T16:02:35.689+0000] {subprocess.py:93} INFO - Please run:
[2024-02-26T16:02:35.689+0000] {subprocess.py:93} INFO - 
[2024-02-26T16:02:35.689+0000] {subprocess.py:93} INFO -   $ gcloud auth login
[2024-02-26T16:02:35.689+0000] {subprocess.py:93} INFO - 
[2024-02-26T16:02:35.690+0000] {subprocess.py:93} INFO - to obtain new credentials.
[2024-02-26T16:02:35.690+0000] {subprocess.py:93} INFO - 
[2024-02-26T16:02:35.690+0000] {subprocess.py:93} INFO - If you have already logged in with a different account, run:
[2024-02-26T16:02:35.690+0000] {subprocess.py:93} INFO - 
[2024-02-26T16:02:35.690+0000] {subprocess.py:93} INFO -   $ gcloud config set account ACCOUNT
[2024-02-26T16:02:35.690+0000] {subprocess.py:93} INFO - 
[2024-02-26T16:02:35.690+0000] {subprocess.py:93} INFO - to select an already authenticated account to use.
[2024-02-26T16:02:35.778+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-26T16:02:35.787+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-26T16:02:35.789+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=yearly, task_id=Send_to_bq, execution_date=20240226T155723, start_date=20240226T160234, end_date=20240226T160235
[2024-02-26T16:02:35.796+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 209 for task Send_to_bq (Bash command failed. The command returned a non-zero exit code 1.; 9515)
[2024-02-26T16:02:35.844+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T16:02:35.859+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
